# Generated by Django 3.2 on 2021-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_age',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='students',
            name='student_gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='students',
            name='student_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
