# Generated by Django 3.2 on 2021-04-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210408_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='school.Students'),
        ),
    ]
